sources:
  paths:
    - /home/flecart/Desktop/old_obsidian/study-notes/master/
    # - /home/flecart/Desktop/old_obsidian/study-notes/other
    # - /home/flecart/Desktop/old_obsidian/study-notes/universita
  images:
    - /home/flecart/Desktop/old_obsidian/image

output:
  base: notes
  path: content/notes
  images: images/notes
  images_path: static/images/notes
  filesystem: /home/flecart/Desktop/website

pipeline:
  # - name: math_convert
  #   options:
  #     engine: mathjax
  - name: remove_after_string
    options:
      string: "# Registro ripassi"
  - name: remove_after_string
    options:
      string: "## Note di ripasso"
  - name: remove_after_string
    options:
      string: "🟩"
      line: true
  - name: remove_after_string
    options:
      string: "🟨"
      line: true
  - name: remove_after_string
    options:
      string: "🟥"
      line: true
  - name: update_frontmatter
    options:
      frontmatter:
        ShowToc: true
        TocOpen: false
  - name: citation_convert
    options: 
      bibfile: /home/flecart/Documents/old_obsidian/zotero.bib
  - name: link_convert
    options: {}
  - name: write_file
    options: {}
