sources:
  paths:
    - /home/flecart/Documents/old_obsidian/study-notes/universita
    - /home/flecart/Documents/old_obsidian/study-notes/other
  images:
    - /home/flecart/Documents/old_obsidian/image

output:
  base: "{{ site.baseurl }}"
  path: notes
  images: images/notes
  filesystem: /home/flecart/Desktop/hot/flecart.github.io

pipeline:
  - name: math_convert
    options: {}
  - name: remove_after_string
    options:
      string: "# Registro ripassi"
  - name: remove_after_string
    options:
      string: "## Note di ripasso"
  - name: update_frontmatter
    options:
      frontmatter:
        layout: page
        tags: "italian"
  - name: citation_convert
    options: 
      bibfile: /home/flecart/Documents/old_obsidian/zotero.bib
  - name: link_convert
    options: {}
  - name: write_file
    options: {}