sources:
  paths:
    - /home/flecart/Documents/old_obsidian/study-notes/universita
    - /home/flecart/Documents/old_obsidian/study-notes/other
  images:
    - /home/flecart/Documents/old_obsidian/image


output:
  base: "{{ site.baseurl }}"
  path: notes
  images: images/notes
  filesystem: /home/flecart/Desktop/hot/flecart.github.io
